M48
; DRILL file {KiCad 8.0.0} date 2024-03-08T02:50:54-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-08T02:50:54-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X2.4026Y-3.5162
X2.4026Y-3.7438
T2
X2.239Y-3.1654
X2.239Y-3.2835
T3
X2.28Y-2.92
X2.28Y-4.34
X4.58Y-2.92
X4.58Y-4.36
M30
